### ISSUE TITLE
Review .css format

### ISSUE THREAD

**Issue by korenmiklos** [REStud/annotated-READMEs#13]
Right now we are calling `mvp.css` directly from the web, but we can put it in the repo and change css styles as needed.

**Comment by csokaimola** [comment]
I think css is ok, I would modify the following:
- more highlight (eg. underline, background color) for compulsory #headers such as "Data Availability Statement", "Computational Requirements",...
- at opening site "Relevant examples of replication packages" list also the software&data used, not only the title (eg. confidential data&stata for "Improving Managament..." because it is misleading now if one ticks more options within software&data categories)

**Comment by korenmiklos** [comment]
- Remove background highlighting from `inline code`.

**Comment by csokaimola** [comment]
I think title (such as eg. here: https://restud.github.io/annotated-READMEs/public/#/package/restud/27118 "Replication Package for: Improving Management with Individual and Group-Based Consulting: Results from a Randomized Experiment in Colombia") should not be highlighted.
